kind: pipeline
type: docker
name: test

steps:
- name: test-backend
  image: python
  environment:
    SECRET_KEY:
      from_secret: SECRET_KEY
    CLIENT_ID:
      from_secret: CLIENT_ID
    CLIENT_SECRET:
      from_secret: CLIENT_SECRET
    DB_PASSWORD:
      from_secret: DB_PASSWORD
  when:
    event:
      - push
  commands:
  - pip install poetry
  - cd backend
  - poetry export -f requirements.txt --dev > requirements.txt
  - pip install -r requirements.txt
  - pytest

services:
- name: database
  image: postgres
  environment:
    POSTGRES_PASSWORD:
      from_secret: DB_PASSWORD
    POSTGRES_USER: postgres
    POSTGRES_DB: test

- name: broker
  image: redis