# Generated by Django 3.2.7 on 2021-09-16 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('filename', models.CharField(max_length=100)),
                ('file_type', models.CharField(default='', max_length=15)),
                ('is_folder', models.BooleanField(default=False)),
                ('file_size', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('storaged_file', models.FileField(null=True, upload_to=main.models.get_file_path)),
                ('number_of_files', models.IntegerField(default=0)),
                ('files_ext_distribution', models.JSONField(default=dict)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.file')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('share_token', models.CharField(max_length=120, unique=True)),
                ('authentication', models.BooleanField(default=False)),
                ('number_of_clicks', models.IntegerField(default=0)),
                ('expire_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.file')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
