# Generated by Django 3.2.6 on 2021-09-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='used_storage',
            field=models.FloatField(default=0),
        ),
    ]
