# Generated by Django 3.2.6 on 2021-09-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_stats_used_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='files_in_use',
            field=models.JSONField(default=[]),
        ),
    ]
