# Generated by Django 3.2.6 on 2021-09-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_stats_files_in_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='files_ext_distribution',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='stats',
            name='files_in_use',
            field=models.JSONField(default=list),
        ),
    ]
