# Generated by Django 3.2.6 on 2021-09-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210913_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='files_in_use',
        ),
    ]
